import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
    zh: {
        title: '戰力追蹤',
        subtitle: '聯盟數據中心 V2',
        guest_mode: '訪客模式',
        admin_tag: '管理員',
        logout: '登出系統',
        personal_entry: '個人填報',
        all_management: '全盟管理',
        footer_text: '© 2026 戰力追蹤',
        admin_login_gate: '管理員伺服器登入口',
        status_operational: '正常運作',
        duel_calculator: '對決計算器',
        monday_calculator: '週一：改裝車提升',
        mon_title: '改裝車提升',
        mon_desc: '強化改裝車零件並清理野外敵對目標獲取積分',
        tuesday_calculator: '週二：建設避難所',
        tue_title: '建設避難所',
        tue_desc: '調整各項數據，即時估算你的對決積分',
        wed_title: '研究科技',
        wed_desc: '提升研發水平並執行城際貿易獲取積分',
        thu_title: '培養英雄',
        thu_desc: '透過招募、消耗碎片與升級英雄獲取積分',
        fri_title: '全面發展',
        fri_desc: '綜合各項日常任務以獲取高額積分',
        sat_title: '擊敗敵軍',
        sat_desc: '透過加速與完成高級任務來展現統治力',
        total_est_score: '總計預估得分',
        reset_data: '重置數據',
        score_base_settings: '積分基準設定',
        base_points_desc: '請依照遊戲內的實際數值，調整各項目的基礎積分（每單位得分）',
        save_and_apply: '儲存設定並套用',
        power_increase: '建築戰力增加',
        power_start: '原本戰力',
        power_end: '提升後戰力',
        power_diff: '差異',
        est_score: '預計得分',
        speedup_title: '建造加速',
        bounty_title: '橙色懸賞任務',
        refine_title: '消耗鍛造石',
        pulse_title: '消耗脈衝模組',
        sur_orange: '橙色避難者',
        sur_purple: '紫色避難者',
        sur_blue: '藍色避難者',
        diamond_gift: '1鑽石禮包',
        speedup_res_title: '科技研發加速',
        tech_power_increase: '科技戰力增加',
        badge_title: '消耗警徽',
        trade_title: '橙色城際貿易',
        unit_trade: '次',
        unit_recruit: '次',
        unit_alloy: '個',
        unit_manual: '本',
        hero_frag_orange: '橙色英雄碎片',
        hero_frag_purple: '紫色英雄碎片',
        hero_frag_blue: '藍色英雄碎片',
        exclusive_frag: '專屬裝備碎片',
        adv_recruit: '高級招募',
        energy_core: '能量核心',
        gear_upgrade: '橙色裝備晉升材料',
        alloy_title: '強化合金',
        skill_manual: '橙色技能手冊',
        radar_title: '雷達事件',
        soldier_title: '訓練士兵',
        soldiers: '士兵',
        soldier_tier: '等級',
        unit_soldier: '名',
        unit_radar: '次',
        unit_drawing: '張',
        unit_wrench: '把',
        unit_case: '個',
        unit_plugin: '個',
        unit_target: '隻',
        unit_gathering: '單位',
        drawing_title: '改裝圖紙',
        wrench_title: '黃金板手',
        module_case: '改裝外裝模組箱子',
        tactical_plugin: '戰術插件箱子',
        snow_leopard: '雪豹',
        polar_zombie: '冰原喪屍',
        gathering_title: '資源採集',
        gathering_coin: 'Z幣',
        gathering_res: '其他資源',
        unit_min: '分',
        unit_hour: '小時',
        unit_day: '天',
        unit_count: '次',
        how_to_check: '如何查看戰力？',
        guide_step_1: '1. 點擊建築（如總部）左上角的「i」圖示',
        guide_step_2: '2. 在清單中即可查看各等級對應的「戰力」',
        close_guide: '我知道了',
        welcome_title: '歡迎使用對決計算器！',
        welcome_desc: '為了獲得 100% 準確的估分，請先點擊右上角的設定按鈕 {icon} 來確認您的基礎積分設定。系統會自動記憶您的數值！',
        dont_show_again: '下次不再顯示',
        unit_item: '個',
        unit_person: '名',
        tips_title: '使用小撇步',
        tips_desc: '點擊右上角的設定按鈕可以自定義您的基礎積分。系統會自動儲存您的設定。',
        dev_in_progress: '開發中',
        calc_dev_desc: '正在根據需求建立其他天的計算邏輯...',
        monday: '週一',
        tuesday: '週二',
        wednesday: '週三',
        thursday: '週四',
        friday: '週五',
        saturday: '週六',
        speedup_1min: '1分鐘任意加速',
        power_10: '提升10點建築戰力',
        build_power_10: '提升10點建築戰力',
        bounty_orange: '執行一次橙色懸賞任務',
        refine_stone: '消耗1個鍛造石',
        pulse_module: '消耗一個脈衝模組',
        survivor_orange: '招募一個橙色避難者',
        survivor_purple: '招募一個紫色避難者',
        survivor_blue: '招募一個藍色避難者',
        diamond_1: '包含1鑽石的禮包',
        speedup_res_1min: '1分鐘科技加速',
        tech_power_10: '提升10點科技戰力',
        badge_1: '消耗1個警徽',
        trade_orange: '執行一次橙色貿易',
        hero_frag_orange: '消耗1個橙色英雄碎片',
        hero_frag_purple: '消耗1個紫色英雄碎片',
        hero_frag_blue: '消耗1個藍色英雄碎片',
        exclusive_frag: '消耗1個專屬裝備碎片',
        adv_recruit: '進行1次高級招募',
        energy_core: '消耗1個能量核心',
        gear_upgrade: '消耗1件橙色裝備',
        alloy_10: '消耗10個強化合金',
        skill_manual: '消耗1本橙色技能手冊',
        radar_1: '完成一次雷達事件',
        soldier_t1: '訓練1名1級士兵',
        soldier_t2: '訓練1名2級士兵',
        soldier_t3: '訓練1名3級士兵',
        soldier_t4: '訓練1名4級士兵',
        soldier_t5: '訓練1名5級士兵',
        soldier_t6: '訓練1名6級士兵',
        soldier_t7: '訓練1名7級士兵',
        soldier_t8: '訓練1名8級士兵',
        soldier_t9: '訓練1名9級士兵',
        soldier_t10: '訓練1名10級士兵',
        drawing_1: '消耗1張改裝圖紙',
        wrench_1: '消耗1個黃金板手',
        plugin_green: '開啟1個綠色插件箱',
        plugin_blue: '開啟1個藍色插件箱',
        plugin_purple: '開啟1個紫色插件箱',
        plugin_orange: '開啟1個橙色插件箱',
        gather_coin: 'Z幣',
        gather_res: '其他資源(木頭,電力,食物)',
        gather_coin_1k: '採集1000 Z幣',
        gather_res_1k: '採集1000 其他資源',
        speedup_accumulate: '累積加速',
        batch_input_mode: '批次填寫模式',
        category_subtotal: '類別小計',
        module_L1: '1個 1級改裝外裝模組',
        module_L2: '1個 2級改裝外裝模組',
        module_L3: '1個 3級改裝外裝模組',
        module_L4: '1個 4級改裝外裝模組',
        module_L5: '1個 5級改裝外裝模組',
        module_L6: '1個 6級改裝外裝模組',
        module_L7: '1個 7級改裝外裝模組',
        sl_10: '擊殺 雪豹 1-10級',
        sl_20: '擊殺 雪豹 11-20級',
        sl_30: '擊殺 雪豹 21-30級',
        sl_40: '擊殺 雪豹 31-40級',
        sl_50: '擊殺 雪豹 41-50級',
        sl_60: '擊殺 雪豹 51-60級',
        pz_10: '擊殺 冰原喪屍 1-10級',
        pz_20: '擊殺 冰原喪屍 11-20級',
        pz_30: '擊殺 冰原喪屍 21-30級',
        pz_40: '擊殺 冰原喪屍 31-40級',
        pz_50: '擊殺 冰原喪屍 41-50級',
        pz_60: '擊殺 冰原喪屍 51-60級',
        level_label: '等級',
        color_green: '綠色',
        color_blue: '藍色',
        color_purple: '紫色',
        color_orange: '橙色',
        preparing_env: '正在準備戰鬥環境...',
        back_to_guest: '← 返回訪客輸入模式',
        login_success: '登入成功！',
        register_success: '註冊成功！',
        op_failed: '操作失敗，請稍後再試',
        email_in_use: '此 Email 已被使用',
        invalid_email: 'Email 格式不正確',
        weak_password: '密碼強度不足（至少6個字元）',
        auth_failed: 'Email 或密碼錯誤',
        google_failed: 'Google 登入失敗，請稍後再試',
        system_name: '遊戲戰力追蹤系統',
        login: '登入',
        register: '註冊',
        password_label: '密碼',
        processing: '處理中...',
        or_text: '或',
        google_login: '使用 Google 登入',


        // UserForm
        form_title: '填寫戰力資料',
        form_desc: '請輸入您的最新英雄戰力資訊，讓盟友掌握戰場動態',
        save_success: '✅ 資料已成功儲存！',
        save_failed: '儲存失敗：',
        error_occurred: '發生錯誤：',
        game_id: '遊戲 ID',
        alliance: '所屬聯盟',
        game_id_placeholder: '例如: KingArthas',
        alliance_placeholder: '例如: LastHope',
        team1: '第一隊戰力 (M)',
        team2: '第二隊戰力 (M)',
        team3: '第三隊戰力 (M)',
        save_data: '儲存資料',
        saving: '儲存中...',
        combat_details: '隊伍戰力詳情',
        current_total: '當前統計總戰力',
        data_preview: '資料預覽',
        sync_notice: '資料將同步至聯盟大數據庫',
        last_updated: '上次更新',
        id_required: '遊戲 ID 為必填',
        alliance_required: '聯盟名稱為必填',

        // AdminPanel
        admin_title: '聯盟數據管理中心',
        admin_desc: '監控分析所有成員的戰力分佈與成長紀錄',
        refresh: '重新整理',
        export_csv: '匯出數據庫',
        preparing_export: '準備下載 CSV...',
        stats_overview: '統計資訊',
        display_count: '顯示人數',
        avg_s1: 'S1 平均',
        avg_s2: 'S2 平均',
        avg_s3: 'S3 平均',
        search_placeholder: '快速搜尋 遊戲 ID 或 聯盟...',
        filter_options: '篩選條件',
        member_id: '成員 ID',
        alliance_label: '所屬聯盟',
        s1_power: 'S1 戰力(M)',
        s2_power: 'S2 戰力(M)',
        s3_power: 'S3 戰力(M)',
        total_eval: '總數據評估',
        update_record: '更新紀錄',
        actions: '操作',
        delete_confirm: '⚠️ 確定要刪除 {id} 的資料嗎？此操作不可恢復。',
        delete_success: '刪除成功',
        edit: '編輯',
        edit_record: '編輯成員紀錄',
        update_success: '更新成功',
        cancel: '取消',
        confirm_save: '儲存修改',
        no_data: '目前尚無成員提交數據',
        no_results: '找不到相關成員數據',
        intel_v2: '聯盟智庫 V2.0 穩定版',
        data_count: '資料筆數',
        loading_data: '全力載入大數據中...',
        alliance_total_power: '聯盟總體戰力',
        alliance_avg_power: '成員平均實力',
        view_members: '成員數據',
        view_alliances: '聯盟分析',
        view_planner: 'SVS戰略規劃',
        total_member: '總成員數',

    },
    en: {
        title: 'Combat Tracker',
        subtitle: 'Alliance Intel V2',
        guest_mode: 'Guest Mode',
        admin_tag: 'ADMIN',
        logout: 'Logout',
        personal_entry: 'Entry Form',
        all_management: 'Dashboard',
        footer_text: '© 2026 Combat Tracker',
        admin_login_gate: 'Admin Server Entrance',
        status_operational: 'Operational',
        duel_calculator: 'Duel Calculator',
        monday_calculator: 'Monday: Mod Vehicle Boost',
        mon_title: 'Mod Vehicle Boost',
        mon_desc: 'Upgrade car parts and eliminate wild targets to earn points',
        tuesday_calculator: 'Tuesday: Base Building',
        tue_title: 'Base Building',
        tue_desc: 'Adjust data to estimate your duel points instantly',
        wed_title: 'Age of Science',
        wed_desc: 'Advance research and intercity trade to earn points',
        thu_title: 'Hero Initiate',
        thu_desc: 'Earn points through recruitment, fragments, and upgrades',
        fri_title: 'Holistic Growth',
        fri_desc: 'Complete various tasks to maximize your score',
        sat_title: 'Enemy Buster',
        sat_desc: 'Demonstrate dominance through tasks and speedups',
        total_est_score: 'Total Estimated Score',
        reset_data: 'Reset Data',
        score_base_settings: 'Score Base Settings',
        base_points_desc: 'Adjust the points earned for each item to match your in-game values',
        save_and_apply: 'Save & Apply',
        power_increase: 'Structure Power Increase',
        power_start: 'Initial Power',
        power_end: 'Target Power',
        power_diff: 'Diff',
        est_score: 'Est. Score',
        speedup_title: 'Construction Speedup',
        bounty_title: 'Orange Bounty',
        refine_title: 'Forging Stone',
        pulse_title: 'Pulse Modules',
        sur_orange: 'Orange Refugee',
        sur_purple: 'Purple Refugee',
        sur_blue: 'Blue Refugee',
        diamond_gift: '1-Diamond Pack',
        speedup_res_title: 'Research Speedup',
        tech_power_increase: 'Tech Power Increase',
        badge_title: 'Badges Consumed',
        trade_title: 'Orange Trade',
        unit_trade: 'times',
        unit_recruit: 'times',
        unit_alloy: 'pcs',
        unit_manual: 'books',
        hero_frag_orange: 'Orange Hero Fragment',
        hero_frag_purple: 'Purple Hero Fragment',
        hero_frag_blue: 'Blue Hero Fragment',
        exclusive_frag: 'Excl. Equipment Fragment',
        adv_recruit: 'Prime Recruitment',
        energy_core: 'Power Core',
        gear_upgrade: 'Orange Equipment as Promotion material',
        alloy_title: 'Enhancement Alloy',
        skill_manual: 'Orange Skill Book',
        radar_title: 'Radar Events',
        soldier_title: 'Train Soldiers',
        soldiers: 'Soldiers',
        soldier_tier: 'Tier',
        unit_soldier: 'soldiers',
        unit_radar: 'times',
        unit_drawing: 'pcs',
        unit_wrench: 'pcs',
        unit_case: 'cases',
        unit_plugin: 'pcs',
        unit_target: 'targets',
        unit_gathering: 'unit',
        drawing_title: 'Modification Blueprint',
        wrench_title: 'Golden Wrench',
        module_case: 'Mod Vehicle Exterior',
        tactical_plugin: 'Tactical Plugin Chest',
        snow_leopard: 'Snow Leopard',
        polar_zombie: 'Frostbane',
        gathering_title: 'Resource Gathering',
        gathering_coin: 'Z-Coin',
        gathering_res: 'Other Resources(wood, electricity, food)',
        unit_min: 'min',
        unit_hour: 'hr',
        unit_day: 'day',
        unit_count: 'times',
        how_to_check: 'How to check power?',
        guide_step_1: '1. Click the "i" icon at the top left of the building (e.g., HQ)',
        guide_step_2: '2. View the "Power" for each level in the list',
        close_guide: 'Got it',
        welcome_title: 'Welcome to Duel Calculator!',
        welcome_desc: 'For 100% accurate scoring, please tap the settings icon {icon} in the top-right to configure your base points. We will remember these for you!',
        dont_show_again: "Don't show this again",
        unit_item: 'pcs',
        unit_person: 'px',
        tips_title: 'Pro Tips',
        tips_desc: 'Click the settings button in the top right to customize your base points. Settings will be saved automatically.',
        dev_in_progress: 'Dev in progress',
        calc_dev_desc: 'Building calculation logic for other days...',
        monday: 'Mon',
        tuesday: 'Tue',
        wednesday: 'Wed',
        thursday: 'Thu',
        friday: 'Fri',
        saturday: 'Sat',
        speedup_1min: '1-min Speedup (Any type)',
        power_10: '10 Structure Power Increase',
        build_power_10: '10 Structure Power Increase',
        bounty_orange: 'Orange Bounty Task',
        refine_stone: 'Forging Stone',
        pulse_module: 'Pulse Module',
        survivor_orange: 'Orange Refugee',
        survivor_purple: 'Purple Refugee',
        survivor_blue: 'Blue Refugee',
        diamond_1: '1-Diamond Pack',
        speedup_res_1min: '1-min Research Speedup',
        tech_power_10: '10 Tech Power Increase',
        badge_1: '1 Badge Consumed',
        trade_orange: '1 Orange Trade Task',
        hero_frag_orange: '1 Orange Hero Fragment',
        hero_frag_purple: '1 Purple Hero Fragment',
        hero_frag_blue: '1 Blue Hero Fragment',
        exclusive_frag: '1 Excl. Equipment Fragment',
        adv_recruit: '1 Prime Recruitment',
        energy_core: '1 Power Core',
        gear_upgrade: '1 Orange Equipment as Promotion material',
        alloy_10: '10 Enhancement Alloy',
        soldier_t10: '1 Tier 10 Soldier',
        drawing_1: '1 Modification Blueprint',
        wrench_1: '1 Golden Wrench',
        plugin_green: '1 Green Tactical Plugin Chest',
        plugin_blue: '1 Blue Tactical Plugin Chest',
        plugin_purple: '1 Purple Tactical Plugin Chest',
        plugin_orange: '1 Orange Tactical Plugin Chest',
        gather_coin: 'Z-Coin',
        gather_res: 'Other Resources(wood, electricity, food)',
        gather_coin_1k: 'Gather 1000 Z-Coins',
        gather_res_1k: 'Gather 1000 Other Res',
        speedup_accumulate: 'Accumulate Speedup',
        batch_input_mode: 'Batch Input Mode',
        category_subtotal: 'Subtotal',
        module_L1: '1 Lv.1 Mod Vehicle Exterior',
        module_L2: '1 Lv.2 Mod Vehicle Exterior',
        module_L3: '1 Lv.3 Mod Vehicle Exterior',
        module_L4: '1 Lv.4 Mod Vehicle Exterior',
        module_L5: '1 Lv.5 Mod Vehicle Exterior',
        module_L6: '1 Lv.6 Mod Vehicle Exterior',
        module_L7: '1 Lv.7 Mod Vehicle Exterior',
        sl_10: 'Kill Snow Leopard Lv.1-10',
        sl_20: 'Kill Snow Leopard Lv.11-20',
        sl_30: 'Kill Snow Leopard Lv.21-30',
        sl_40: 'Kill Snow Leopard Lv.31-40',
        sl_50: 'Kill Snow Leopard Lv.41-50',
        sl_60: 'Kill Snow Leopard Lv.51-60',
        pz_10: 'Kill Frostbane Lv.1-10',
        pz_20: 'Kill Frostbane Lv.11-20',
        pz_30: 'Kill Frostbane Lv.21-30',
        pz_40: 'Kill Frostbane Lv.31-40',
        pz_50: 'Kill Frostbane Lv.41-50',
        pz_60: 'Kill Frostbane Lv.51-60',
        level_label: 'Lv',
        color_green: 'Green',
        color_blue: 'Blue',
        color_purple: 'Purple',
        color_orange: 'Orange',
        radar_1: '1 Radar Event Completed',
        soldier_t1: '1 Tier 1 Soldier',
        soldier_t2: '1 Tier 2 Soldier',
        soldier_t3: '1 Tier 3 Soldier',
        soldier_t4: '1 Tier 4 Soldier',
        soldier_t5: '1 Tier 5 Soldier',
        soldier_t6: '1 Tier 6 Soldier',
        soldier_t7: '1 Tier 7 Soldier',
        soldier_t8: '1 Tier 8 Soldier',
        soldier_t9: '1 Tier 9 Soldier',
        soldier_t10: '1 Tier 10 Soldier',
        loading_system: 'Initializing Combat System...',
        preparing_env: 'Preparing Combat Environment...',
        back_to_guest: '← Back to Guest Mode',
        login_success: 'Login successful!',
        register_success: 'Registration successful!',
        op_failed: 'Operation failed, please try again later',
        email_in_use: 'This Email is already in use',
        invalid_email: 'Invalid Email format',
        weak_password: 'Password too weak (at least 6 characters)',
        auth_failed: 'Invalid Email or password',
        google_failed: 'Google login failed, please try again',
        system_name: 'Game Power Tracker',
        login: 'Login',
        register: 'Register',
        password_label: 'Password',
        processing: 'Processing...',
        or_text: 'Or',
        google_login: 'Sign in with Google',


        // UserForm
        form_title: 'Power Data Entry',
        form_desc: 'Enter your latest hero power info to keep allies updated',
        save_success: '✅ Data saved successfully!',
        save_failed: 'Save failed: ',
        error_occurred: 'Error occurred: ',
        game_id: 'Game ID',
        alliance: 'Alliance',
        game_id_placeholder: 'e.g., KingArthas',
        alliance_placeholder: 'e.g., LastHope',
        team1: 'Team 1 Power (M)',
        team2: 'Team 2 Power (M)',
        team3: 'Team 3 Power (M)',
        save_data: 'Save Data',
        saving: 'Saving...',
        combat_details: 'Team Power Details',
        current_total: 'Total Combat Power',
        data_preview: 'Data Preview',
        sync_notice: 'Data will be synced to Alliance database',
        last_updated: 'Last updated',
        id_required: 'Game ID is required',
        alliance_required: 'Alliance name is required',

        // AdminPanel
        admin_title: 'Alliance Intel Center',
        admin_desc: 'Monitor and analyze member power distribution',
        refresh: 'Refresh',
        export_csv: 'Export CSV',
        preparing_export: 'Preparing CSV download...',
        stats_overview: 'Statistics',
        display_count: 'Members',
        avg_s1: 'S1 Avg',
        avg_s2: 'S2 Avg',
        avg_s3: 'S3 Avg',
        search_placeholder: 'Search Game ID or Alliance...',
        filter_options: 'Filters',
        member_id: 'Member ID',
        alliance_label: 'Alliance',
        s1_power: 'S1 Power(M)',
        s2_power: 'S2 Power(M)',
        s3_power: 'S3 Power(M)',
        total_eval: 'Total Eval',
        update_record: 'Update Record',
        actions: 'Action',
        delete_confirm: '⚠️ Are you sure you want to delete {id}? This cannot be undone.',
        delete_success: 'Deleted successfully',
        edit: 'Edit',
        edit_record: 'Edit Member Record',
        update_success: 'Update successful',
        cancel: 'Cancel',
        confirm_save: 'Save Changes',
        no_data: 'No data submitted yet',
        no_results: 'No matching records found',
        intel_v2: 'Alliance Intel V2.0 Stable',
        data_count: 'Total Records',
        loading_data: 'Loading Big Data...',
        alliance_total_power: 'Total Alliance Power',
        alliance_avg_power: 'Avg Member Power',
        view_members: 'Members',
        view_alliances: 'Alliances',
        view_planner: 'SVS Strategy',
        total_member: 'Total Members',

    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState(localStorage.getItem('preferred_lang') || 'zh');

    const t = (key) => {
        return translations[lang][key] || key;
    };

    const toggleLang = () => {
        const newLang = lang === 'zh' ? 'en' : 'zh';
        setLang(newLang);
        localStorage.setItem('preferred_lang', newLang);
    };

    return (
        <LanguageContext.Provider value={{ lang, t, toggleLang }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
