import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
    zh: {
        title: '戰力追蹤',
        subtitle: '聯盟數據中心 V2',
        guest_mode: '訪客模式',
        admin_tag: '管理員',
        logout: '登出系統',
        personal_entry: '個人填報',
        all_management: '全盟管理',
        footer_text: '© 2026 戰力追蹤',
        admin_login_gate: '管理員伺服器登入口',
        status_operational: '正常運作',
        duel_calculator: '對決計算器',
        tuesday_calculator: '週二：建設避難所',
        tue_title: '建設避難所分數預測',
        tue_desc: '調整各項數據，即時估算你的對決積分',
        wed_title: '研究科技分數預測',
        wed_desc: '提升研發水平並執行城際貿易獲取積分',
        total_est_score: '總計預估得分',
        reset_data: '重置數據',
        score_base_settings: '積分基準設定',
        base_points_desc: '根據您的科技等級調整各項目的基礎分（每單位積分）',
        save_and_apply: '儲存設定並套用',
        power_increase: '建築戰力增加',
        power_start: '原本戰力',
        power_end: '提升後戰力',
        power_diff: '差異',
        est_score: '預計得分',
        speedup_title: '建造加速',
        bounty_title: '橙色懸賞任務',
        refine_title: '消耗鍛造石',
        pulse_title: '消耗脈衝模組',
        sur_orange: '橙色避難者',
        sur_purple: '紫色避難者',
        sur_blue: '藍色避難者',
        diamond_gift: '1鑽石禮包',
        speedup_res_title: '科技研發加速',
        tech_power_increase: '科技戰力增加',
        badge_title: '消耗警徽',
        trade_title: '橙色城際貿易',
        unit_trade: '次',
        unit_min: '分',
        unit_hour: '小時',
        unit_day: '天',
        unit_count: '次',
        how_to_check: '如何查看戰力？',
        guide_step_1: '1. 點擊建築（如總部）左上角的「i」圖示',
        guide_step_2: '2. 在清單中即可查看各等級對應的「戰力」',
        close_guide: '我知道了',
        welcome_title: '歡迎使用對決計算器！',
        welcome_desc: '為了獲得 100% 準確的估分，請先點擊右上角的設定按鈕 {icon} 來配置您的基礎積分（科技加成）。設定後系統將會自動記憶！',
        dont_show_again: '下次不再顯示',
        unit_item: '個',
        unit_person: '名',
        tips_title: '使用小撇步',
        tips_desc: '點擊右上角的設定按鈕可以自定義您的基礎積分（根據科技加成）。系統會自動儲存您的設定。',
        dev_in_progress: '開發中',
        calc_dev_desc: '正在根據需求建立其他天的計算邏輯...',
        monday: '週一',
        tuesday: '週二',
        wednesday: '週三',
        thursday: '週四',
        friday: '週五',
        saturday: '週六',
        speedup_1min: '1分鐘建造加速',
        power_10: '提升10點建築戰力',
        bounty_orange: '執行一次橙色懸賞任務',
        refine_stone: '消耗1個鍛造石',
        pulse_module: '消耗一個脈衝模組',
        survivor_orange: '招募一個橙色避難者',
        survivor_purple: '招募一個紫色避難者',
        survivor_blue: '招募一個藍色避難者',
        diamond_1: '包含1鑽石的禮包',
        speedup_res_1min: '1分鐘科技加速',
        tech_power_10: '提升10點科技戰力',
        badge_1: '消耗1個警徽',
        trade_orange: '執行一次橙色貿易',
        loading_system: '正在初始化戰力系統...',
        preparing_env: '正在準備戰鬥環境...',
        back_to_guest: '← 返回訪客輸入模式',
        login_success: '登入成功！',
        register_success: '註冊成功！',
        op_failed: '操作失敗，請稍後再試',
        email_in_use: '此 Email 已被使用',
        invalid_email: 'Email 格式不正確',
        weak_password: '密碼強度不足（至少6個字元）',
        auth_failed: 'Email 或密碼錯誤',
        google_failed: 'Google 登入失敗，請稍後再試',
        system_name: '遊戲戰力追蹤系統',
        login: '登入',
        register: '註冊',
        password_label: '密碼',
        processing: '處理中...',
        or_text: '或',
        google_login: '使用 Google 登入',


        // UserForm
        form_title: '填寫戰力資料',
        form_desc: '請輸入您的最新英雄戰力資訊，讓盟友掌握戰場動態',
        save_success: '✅ 資料已成功儲存！',
        save_failed: '儲存失敗：',
        error_occurred: '發生錯誤：',
        game_id: '遊戲 ID',
        alliance: '所屬聯盟',
        game_id_placeholder: '例如: KingArthas',
        alliance_placeholder: '例如: LastHope',
        team1: '第一隊戰力 (M)',
        team2: '第二隊戰力 (M)',
        team3: '第三隊戰力 (M)',
        save_data: '儲存資料',
        saving: '儲存中...',
        combat_details: '隊伍戰力詳情',
        current_total: '當前統計總戰力',
        data_preview: '資料預覽',
        sync_notice: '資料將同步至聯盟大數據庫',
        last_updated: '上次更新',
        id_required: '遊戲 ID 為必填',
        alliance_required: '聯盟名稱為必填',

        // AdminPanel
        admin_title: '聯盟數據管理中心',
        admin_desc: '監控分析所有成員的戰力分佈與成長紀錄',
        refresh: '重新整理',
        export_csv: '匯出數據庫',
        preparing_export: '準備下載 CSV...',
        stats_overview: '統計資訊',
        display_count: '顯示人數',
        avg_s1: 'S1 平均',
        avg_s2: 'S2 平均',
        avg_s3: 'S3 平均',
        search_placeholder: '快速搜尋 遊戲 ID 或 聯盟...',
        filter_options: '篩選條件',
        member_id: '成員 ID',
        alliance_label: '所屬聯盟',
        s1_power: 'S1 戰力(M)',
        s2_power: 'S2 戰力(M)',
        s3_power: 'S3 戰力(M)',
        total_eval: '總數據評估',
        update_record: '更新紀錄',
        actions: '操作',
        delete_confirm: '⚠️ 確定要刪除 {id} 的資料嗎？此操作不可恢復。',
        delete_success: '刪除成功',
        edit: '編輯',
        edit_record: '編輯成員紀錄',
        update_success: '更新成功',
        cancel: '取消',
        confirm_save: '儲存修改',
        no_data: '目前尚無成員提交數據',
        no_results: '找不到相關成員數據',
        intel_v2: '聯盟智庫 V2.0 穩定版',
        data_count: '資料筆數',
        loading_data: '全力載入大數據中...',
        alliance_total_power: '聯盟總體戰力',
        alliance_avg_power: '成員平均實力',
        view_members: '成員數據',
        view_alliances: '聯盟分析',
        view_planner: 'SVS戰略規劃',
        total_member: '總成員數',

    },
    en: {
        title: 'Combat Tracker',
        subtitle: 'Alliance Intel V2',
        guest_mode: 'Guest Mode',
        admin_tag: 'ADMIN',
        logout: 'Logout',
        personal_entry: 'Entry Form',
        all_management: 'Dashboard',
        footer_text: '© 2026 Combat Tracker',
        admin_login_gate: 'Admin Server Entrance',
        status_operational: 'Operational',
        duel_calculator: 'Duel Calculator',
        tuesday_calculator: 'Tuesday: Base Building',
        tue_title: 'Base Building Score Predictor',
        tue_desc: 'Adjust data to estimate your duel points instantly',
        wed_title: 'Research Tech Score Predictor',
        wed_desc: 'Advance research and intercity trade to earn points',
        total_est_score: 'Total Estimated Score',
        reset_data: 'Reset Data',
        score_base_settings: 'Score Base Settings',
        base_points_desc: 'Adjust base points for each item based on your tech level',
        save_and_apply: 'Save & Apply',
        power_increase: 'Building Power Increase',
        power_start: 'Initial Power',
        power_end: 'Target Power',
        power_diff: 'Diff',
        est_score: 'Est. Score',
        speedup_title: 'Construction Speedup',
        bounty_title: 'Orange Bounty',
        refine_title: 'Forging Stone',
        pulse_title: 'Pulse Modules',
        sur_orange: 'Orange Refugee',
        sur_purple: 'Purple Refugee',
        sur_blue: 'Blue Refugee',
        diamond_gift: '1-Diamond Pack',
        speedup_res_title: 'Research Speedup',
        tech_power_increase: 'Tech Power Increase',
        badge_title: 'Badges Consumed',
        trade_title: 'Orange Trade',
        unit_trade: 'times',
        unit_min: 'min',
        unit_hour: 'hr',
        unit_day: 'day',
        unit_count: 'times',
        how_to_check: 'How to check power?',
        guide_step_1: '1. Click the "i" icon at the top left of the building (e.g., HQ)',
        guide_step_2: '2. View the "Power" for each level in the list',
        close_guide: 'Got it',
        welcome_title: 'Welcome to Duel Calculator!',
        welcome_desc: 'For 100% accurate scoring, please tap the settings icon {icon} in the top-right to configure your base points (tech bonuses). We will remember these for you!',
        dont_show_again: "Don't show this again",
        unit_item: 'pcs',
        unit_person: 'px',
        tips_title: 'Pro Tips',
        tips_desc: 'Click the settings button in the top right to customize your base points. Settings will be saved automatically.',
        dev_in_progress: 'Dev in progress',
        calc_dev_desc: 'Building calculation logic for other days...',
        monday: 'Mon',
        tuesday: 'Tue',
        wednesday: 'Wed',
        thursday: 'Thu',
        friday: 'Fri',
        saturday: 'Sat',
        speedup_1min: '1-min Construction Speedup',
        power_10: '10 Building Power Increase',
        bounty_orange: 'Orange Bounty Task',
        refine_stone: 'Forging Stone',
        pulse_module: 'Pulse Module',
        survivor_orange: 'Orange Refugee',
        survivor_purple: 'Purple Refugee',
        survivor_blue: 'Blue Refugee',
        diamond_1: '1-Diamond Pack',
        speedup_res_1min: '1-min Research Speedup',
        tech_power_10: '10 Tech Power Increase',
        badge_1: '1 Badge Consumed',
        trade_orange: '1 Orange Trade Task',
        loading_system: 'Initializing Combat System...',
        preparing_env: 'Preparing Combat Environment...',
        back_to_guest: '← Back to Guest Mode',
        login_success: 'Login successful!',
        register_success: 'Registration successful!',
        op_failed: 'Operation failed, please try again later',
        email_in_use: 'This Email is already in use',
        invalid_email: 'Invalid Email format',
        weak_password: 'Password too weak (at least 6 characters)',
        auth_failed: 'Invalid Email or password',
        google_failed: 'Google login failed, please try again',
        system_name: 'Game Power Tracker',
        login: 'Login',
        register: 'Register',
        password_label: 'Password',
        processing: 'Processing...',
        or_text: 'Or',
        google_login: 'Sign in with Google',


        // UserForm
        form_title: 'Power Data Entry',
        form_desc: 'Enter your latest hero power info to keep allies updated',
        save_success: '✅ Data saved successfully!',
        save_failed: 'Save failed: ',
        error_occurred: 'Error occurred: ',
        game_id: 'Game ID',
        alliance: 'Alliance',
        game_id_placeholder: 'e.g., KingArthas',
        alliance_placeholder: 'e.g., LastHope',
        team1: 'Team 1 Power (M)',
        team2: 'Team 2 Power (M)',
        team3: 'Team 3 Power (M)',
        save_data: 'Save Data',
        saving: 'Saving...',
        combat_details: 'Team Power Details',
        current_total: 'Total Combat Power',
        data_preview: 'Data Preview',
        sync_notice: 'Data will be synced to Alliance database',
        last_updated: 'Last updated',
        id_required: 'Game ID is required',
        alliance_required: 'Alliance name is required',

        // AdminPanel
        admin_title: 'Alliance Intel Center',
        admin_desc: 'Monitor and analyze member power distribution',
        refresh: 'Refresh',
        export_csv: 'Export CSV',
        preparing_export: 'Preparing CSV download...',
        stats_overview: 'Statistics',
        display_count: 'Members',
        avg_s1: 'S1 Avg',
        avg_s2: 'S2 Avg',
        avg_s3: 'S3 Avg',
        search_placeholder: 'Search Game ID or Alliance...',
        filter_options: 'Filters',
        member_id: 'Member ID',
        alliance_label: 'Alliance',
        s1_power: 'S1 Power(M)',
        s2_power: 'S2 Power(M)',
        s3_power: 'S3 Power(M)',
        total_eval: 'Total Eval',
        update_record: 'Update Record',
        actions: 'Action',
        delete_confirm: '⚠️ Are you sure you want to delete {id}? This cannot be undone.',
        delete_success: 'Deleted successfully',
        edit: 'Edit',
        edit_record: 'Edit Member Record',
        update_success: 'Update successful',
        cancel: 'Cancel',
        confirm_save: 'Save Changes',
        no_data: 'No data submitted yet',
        no_results: 'No matching records found',
        intel_v2: 'Alliance Intel V2.0 Stable',
        data_count: 'Total Records',
        loading_data: 'Loading Big Data...',
        alliance_total_power: 'Total Alliance Power',
        alliance_avg_power: 'Avg Member Power',
        view_members: 'Members',
        view_alliances: 'Alliances',
        view_planner: 'SVS Strategy',
        total_member: 'Total Members',

    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState(localStorage.getItem('preferred_lang') || 'zh');

    const t = (key) => {
        return translations[lang][key] || key;
    };

    const toggleLang = () => {
        const newLang = lang === 'zh' ? 'en' : 'zh';
        setLang(newLang);
        localStorage.setItem('preferred_lang', newLang);
    };

    return (
        <LanguageContext.Provider value={{ lang, t, toggleLang }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
